ALTER TABLE action Engine=InnoDB;
ALTER TABLE actionarchive ENGINE=INNODB;
ALTER TABLE actiontype ENGINE=INNODB;
ALTER TABLE aggregatetype ENGINE=INNODB;
ALTER TABLE assoctype ENGINE=INNODB;
ALTER TABLE authentication ENGINE=INNODB;
ALTER TABLE backtracking ENGINE=INNODB;
ALTER TABLE easyrec ENGINE=INNODB;
ALTER TABLE idmapping ENGINE=INNODB;
ALTER TABLE item ENGINE=INNODB;
ALTER TABLE itemassoc ENGINE=INNODB;
ALTER TABLE itemtype ENGINE=INNODB;
ALTER TABLE operator ENGINE=INNODB;
ALTER TABLE profile ENGINE=INNODB;
ALTER TABLE recommendation ENGINE=INNODB;
ALTER TABLE recommendeditem ENGINE=INNODB;
ALTER TABLE ruleminerlog ENGINE=INNODB;
ALTER TABLE sourcetype ENGINE=INNODB;
ALTER TABLE tenant ENGINE=INNODB;
ALTER TABLE viewtype ENGINE=INNODB;

ALTER TABLE profile ADD COLUMN active TINYINT(1) NOT NULL DEFAULT '1';

CREATE TABLE plugin (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  displayname VARCHAR(150) DEFAULT NULL,
  pluginid VARCHAR(500) NOT NULL,
  version VARCHAR(50) NOT NULL,
  origfilename VARCHAR(150) DEFAULT '',
  state VARCHAR(50) NOT NULL,
  file LONGBLOB,
  changeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY pluginId (pluginid, version)
) ENGINE=INNODB DEFAULT CHARSET=latin1 COMMENT='Table containing plugins';

ALTER TABLE sourcetype MODIFY name VARCHAR(250);

ALTER TABLE ruleminerlog ADD COLUMN pluginId VARCHAR(500) NOT NULL AFTER tenantId;
ALTER TABLE ruleminerlog ADD COLUMN pluginVersion VARCHAR(50) NOT NULL AFTER pluginId;

TRUNCATE TABLE easyrec;
INSERT INTO easyrec (version) VALUES (0.95);